# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

# A docker compose file for spinning up local infrastructure with or without dockerized pygeoapi
# To spin up pygeoapi use the --profile production flag otherwise run with uv for hot reloading

# this docker compose is not used for production, only for development
services:
  pygeoapi:
    build:
      context: .
      dockerfile: pygeoapi-deployment/Dockerfile
    ports:
      - 5005:80
    env_file:
      - .env.example
    environment:
      - REDIS_HOST=redis
      - PYGEOAPI_URL=http://localhost:5005
      - COLLECTOR_ENDPOINT=jaeger
      - OTEL_SDK_DISABLED=${OTEL_SDK_DISABLED:-false}
      - POSTGRES_HOST=database
    depends_on:
      - redis
      - database
    profiles:
      - production

  database:
    image: postgis/postgis:17-3.6-alpine
    platform: linux/amd64

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeMe
      POSTGRES_DB: edr

    ports:
      - "5432:5432"

    volumes:
      - awo_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: >
        CMD-SHELL
        pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
      interval: 10s
      timeout: 8s
      retries: 5

  redis:
    image: redislabs/redismod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # this is not needed in production, solely used for visualizing
  # traces and debugging performance issues
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      # Ports defined here https://www.jaegertracing.io/docs/next-release/getting-started/#all-in-one
      - "16686:16686" # expose the UI
      - "4317:4317" # expose the OTLP HTTP port
    environment:
      - LOG_LEVEL=debug
    restart: on-failure

  dashboard-ui:
    build:
      context: dashboard-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    profiles:
      - ui

volumes:
  redis_data: 
  awo_postgres_data: