# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

[project]
name = "nationalwatermodeletlgroundwater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Colton Loftus", email = "70598503+C-Loftus@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"
