# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

[project]
name = "NationalWaterModel"
version = "0.1.0"
description = "EDR support for the national water model"
readme = "README.md"
authors = [
    { name = "Colton Loftus", email = "70598503+C-Loftus@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "s3fs>=2025.9.0",
    "xarray>=2025.4.0",
    "zarr>=2.18.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
